{{- if .Values.prow.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-secret: jx-basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
{{- if .Values.cluster.ingress.annotations }}
{{ toYaml .Values.cluster.ingress.annotations | indent 4 }}
{{- end }}
  name: tide
spec:
  rules:
  - host: tide{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
    http:
      paths:
      - backend:
          serviceName: tide
          servicePort: 80
{{- if .Values.cluster.tls }}
  tls:
  - hosts:
    - tide{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
{{- if .Values.tide.ingress.tls.secretName }}
    secretName: "{{ .Values.tide.ingress.tls.secretName }}"
{{- else if .Values.cluster.ingress.tls.secretName }}
    secretName: "{{ .Values.cluster.ingress.tls.secretName }}"
{{- else if eq .Values.certmanager.production "true" }}
    secretName: "tls-{{ .Values.cluster.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Values.cluster.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}
{{- end }}
