{{- if index .Values "docker-registry" "enabled" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-secret: jx-basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
{{- if .Values.cluster.ingress.annotations }}
{{ toYaml .Values.cluster.ingress.annotations | indent 4 }}
{{- end }}
  name: docker-registry
spec:
  rules:
  - host: docker-registry{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
    http:
      paths:
      - backend:
          serviceName: jenkins-x-docker-registry
          servicePort: 5000
{{- if .Values.cluster.tls }}
  tls:
  - hosts:
    - docker-registry{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
{{- if index .Values "docker-registry" "ingress" "tls" "secretName" }}
    secretName: "{{ index .Values "docker-registry" "ingress" "tls" "secretName" }}"
{{- else if .Values.cluster.ingress.tls.secretName }}
    secretName: "{{ .Values.cluster.ingress.tls.secretName }}"
{{- else if eq .Values.certmanager.production "true" }}
    secretName: "tls-{{ .Values.cluster.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Values.cluster.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}
{{- end }}
