{{- if index .Values "jenkins-x-platform" "chartmuseum" "enabled" }}
{{- if index .Values "jenkins-x-platform" "chartmuseum" "ingress" "enabled" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
{{- if .Values.cluster.ingress.annotations }}
{{ toYaml .Values.cluster.ingress.annotations | indent 4 }}
{{- end }}
  name: chartmuseum
spec:
  rules:
  - host: chartmuseum{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
    http:
      paths:
      - backend:
          serviceName: jenkins-x-chartmuseum
          servicePort: 8080
{{- if .Values.cluster.tls }}
  tls:
  - hosts:
    - chartmuseum{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
{{- if .Values.chartmuseum.ingress.tls.secretName }}
    secretName: "{{ .Values.chartmuseum.ingress.tls.secretName }}"
{{- else if .Values.cluster.ingress.tls.secretName }}
    secretName: "{{ .Values.cluster.ingress.tls.secretName }}"
{{- else if eq .Values.certmanager.production "true" }}
    secretName: "tls-{{ .Values.cluster.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Values.cluster.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}
{{- end }}
{{- end }}
